services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      # EntryPoints
      - "--entrypoints.web.address=:80"

      # Providers 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"

      # API & Dashboard 
      - "--api.dashboard=true"
      - "--api.insecure=true"

      # Observability 
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      # Traefik needs access to docker to see the containers (read-only)
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
    labels:
      # Tells Traefik this container should be exposed
      - "traefik.enable=true"
      # Defines when to route traffic to this container
      - "traefik.http.routers.dashboard.rule=Host(`traefik.kaos`)"
      # Tells Traefik which entrypoint the router listens on (web = HTTP port 80; websecure = 443)
      - "traefik.http.routers.dashboard.entrypoints=web"
      # Sends traffic to Traefik dashboard, not a container
      - "traefik.http.routers.dashboard.service=api@internal"

networks:
  traefik:
    name: traefik
    driver: bridge